# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrbf4mbElhZxfJ9DuL-zIqxSHugG_Enf

**Mini Project(Mini Calculator):**
"""

def Addition (num1,num2):
  sum=num1+num2
  return sum

def Subtraction(num1,num2):
  sub=num1-num2
  return sub

def Multiplication(num1,num2):
  mult=num1*num2
  return mult

def Division(num1,num2):
  div=num1/num2
  return div

def calc(command,num1,num2):
  if command=="add":
    print(Addition(num1,num2))
  elif command=="sub":
    print(Subtraction(num1,num2))
  elif command=="mult":
    print(Multiplication(num1,num2))
  elif command=="div":
    print(Division(num1,num2))