# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16byPptaNVLR8he1KgDFRTd8QLeFVTYEa
"""

import calculator
from calculator import calc

answer="yes"
while (answer=="yes"):
  n1=input("enter first number:")
  n2=input("enter second number:")
  command=input("enter the operation(add/sub/mult/div):")
  print("the result is:")
  calc(command,int(n1),int(n2))
  answer=input("do you want to make another operation?(yes/no)")